server:
  port: 8729
spring:
  application:
    name: charlie-manage
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html#/
